@startuml

class Solution43 {
String siteName
String siteAuthor
Boolean jsFolder
Boolean cssFolder
main()
}

class websiteTemplate{
String siteName
String siteAuthor
File index

createJsFolder()
createCssFolder()
createIndexFile()

}

Solution43 -- websiteTemplate

@enduml