@startuml

class Solution43 {
main()
}

class websiteTemplate{
-String siteName
-String siteAuthor
-Path websiteRoot

-createJsFolder()
-createCssFolder()
-createIndexFile()

}

Solution43 -- websiteTemplate

@enduml